# ----------- CONFIGURABLE START -----------
title:            "NoahNye|小菜鸟|jekyll blog|GitHub blog"
description:      "学习中|欢迎来到 NoahNye「角落」侃侃理想、谈谈人生、敲敲代码。"
url:             http://noahnye.tk/ # 域名
signoff:          "NoahNye" # Your name
facebook_appid:   #liberxue
google_analytics: UA-110796272-1
share:            true 
# 分页
paginate: 6
paginate_path: "noahnyepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         旅游
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
